name: CI - RWAN10T (.NET 10)

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # =========================
      # Checkout
      # =========================
      - name: Checkout repository
        uses: actions/checkout@v4

      # =========================
      # SQL Server
      # =========================
      - name: Start SQL Server container
        run: |
          docker run -d --name sqlserver_test \
            -e "ACCEPT_EULA=Y" \
            -e "MSSQL_SA_PASSWORD=@Admin123" \
            -p 1433:1433 \
            mcr.microsoft.com/mssql/server:2022-latest

          echo "Waiting SQL Server..."
          timeout 120s bash -c "until docker exec sqlserver_test /opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P '@Admin123' -Q 'SELECT 1' -C; do sleep 5; done"

      - name: Create database
        run: |
          docker exec sqlserver_test /opt/mssql-tools18/bin/sqlcmd \
            -S localhost -U SA -P '@Admin123' \
            -Q "IF DB_ID('RWAN10T') IS NULL CREATE DATABASE [RWAN10T]" -C

      # =========================
      # .NET setup
      # =========================
      - name: Setup .NET 10
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      # =========================
      # Build pipeline
      # =========================
      - name: Restore dependencies
        run: dotnet restore
        working-directory: RWAN10T.Api

      - name: Build solution
        run: dotnet build -c Release --no-restore
        working-directory: RWAN10T.Api

      - name: Run tests
        run: dotnet test -c Release --no-build --logger "console;verbosity=detailed"
        working-directory: RWAN10T.Api

      # =========================
      # Docker build
      # =========================
      - name: Docker compose build
        run: docker compose build
        working-directory: RWAN10T.Api

      # =========================
      # Docker Hub login
      # =========================
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      # =========================
      # Push image
      # =========================
      - name: Build & Push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/RWAN10T:latest .

          docker tag ${{ secrets.DOCKER_USERNAME }}/RWAN10T:latest \
                     ${{ secrets.DOCKER_USERNAME }}/RWAN10T:${{ github.run_id }}

          docker push ${{ secrets.DOCKER_USERNAME }}/RWAN10T:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/RWAN10T:${{ github.run_id }}